defaults: &defaults
  adapter: mysql
  encoding: utf8
  username: beecookuser 
  password: beecookokbest
  host: localhost

development:
  database: beecook_development
  <<: *defaults

test:
  database: beecook_test 
  <<: *defaults

production:
  database: beecook_alpha
  <<: *defaults
